'\" t
.TH "BUXTONCTL" "1" "" "buxton 1" "buxtonctl"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
buxtonctl \- Manipulates data stored in the buxton configuration
system

.SH "SYNOPSIS"
.HP \w'\fBbuxtonctl\fR\ 'u
\fBbuxtonctl\fR [OPTIONS...] COMMAND ARGS

.SH "DESCRIPTION"
.PP
\fBbuxtonctl\fR
is used to modify and query configuration, as managed by
\fBbuxton\fR(7)\&.

.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints a help message\&.
.RE
.PP
\fB\-d\fR, \fB\-\-direct\fR
.RS 4
Modifies the configuration directly, without connecting to
\fBbuxtond\fR(8)\&. Note that this is a privileged operation\&.
.RE
.PP
\fB\-c\fR FILE, \fB\-\-config\-file\fR FILE
.RS 4
Path to a buxton configuration file (see \fBbuxton\&.conf\fR(5))\&.
.RE

.SH "COMMANDS"
.PP
The following commands are understood:
.SS "Group manipulation"
.PP
\fBcreate\-group\fR LAYER GROUP
.RS 4
Creates a group within the specified layer\&.
.RE
.PP
\fBset\-label\fR LAYER GROUP LABEL
.RS 4
Sets the Smack label for the group in the specified layer\&. Note
that this is a privileged operation\&.
.RE
.PP
\fBremove\-group\fR LAYER GROUP
.RS 4
Removes a group within the specified layer\&. Note that this
operation recursively removes all keys within the given group\&.
.RE
.SS "Key manipulation"
.PP
Note that all "get" commands accept an optional LAYER argument\&.
Without specifying the layer, the returned value will be taken from
the layer with highest priority that the client has permission to
read\&. With the layer argument, buxton will try to return the key
value only from the given layer\&.
.PP
\fBget\-string\fR [LAYER] GROUP KEY
.RS 4
Gets a key value with string type\&.
.RE
.PP
\fBset\-string\fR LAYER GROUP KEY VALUE
.RS 4
Sets a key value with string type\&.
.RE
.PP
\fBget\-int32\fR [LAYER] GROUP KEY
.RS 4
Gets a key value with int32_t type\&.
.RE
.PP
\fBset\-int32\fR LAYER GROUP KEY VALUE
.RS 4
Sets a key value with string type\&.
.RE
.PP
\fBget\-uint32\fR [LAYER] GROUP KEY
.RS 4
Gets a key value with uint32_t type\&.
.RE
.PP
\fBset\-uint32\fR LAYER GROUP KEY VALUE
.RS 4
Sets a key value with uint32_t type\&.
.RE
.PP
\fBget\-int64\fR [LAYER] GROUP KEY
.RS 4
Gets a key value with int64_t type\&.
.RE
.PP
\fBset\-int64\fR LAYER GROUP KEY VALUE
.RS 4
Sets a key value with int64_t type\&.
.RE
.PP
\fBget\-uint64\fR [LAYER] GROUP KEY
.RS 4
Gets a key value with uint64_t type\&.
.RE
.PP
\fBset\-uint64\fR LAYER GROUP KEY VALUE
.RS 4
Sets a key value with uint64_t type\&.
.RE
.PP
\fBget\-float\fR [LAYER] GROUP KEY
.RS 4
Gets a key value with float type\&.
.RE
.PP
\fBset\-float\fR LAYER GROUP KEY VALUE
.RS 4
Sets a key value with float type\&.
.RE
.PP
\fBget\-double\fR [LAYER] GROUP KEY
.RS 4
Gets a key value with double type\&.
.RE
.PP
\fBset\-double\fR LAYER GROUP KEY VALUE
.RS 4
Sets a key value with double type\&.
.RE
.PP
\fBget\-bool\fR [LAYER] GROUP KEY
.RS 4
Gets a key value with boolean type\&.
.RE
.PP
\fBset\-bool\fR LAYER GROUP KEY VALUE
.RS 4
Sets a key value with boolean type\&.
.RE
.PP
\fBset\-label\fR LAYER GROUP KEY LABEL
.RS 4
Sets the Smack label on a key\&. Note that this is a privileged
operation\&.
.RE
.PP
\fBunset\-value\fR LAYER GROUP KEY
.RS 4
Unset the value on a key\&. This removes the key from the given
group\&.
.RE

.SH "ENVIRONMENT VARIABLES"
.PP
\fI$BUXTON_CONF_FILE\fR
.RS 4
The path to a buxton configuration file (see
\fBbuxton\&.conf\fR(5))\&.
.RE
.PP
\fI$BUXTON_MODULE_DIR\fR
.RS 4
The directory in which buxton's backend modules reside\&.
.RE
.PP
\fI$BUXTON_DB_PATH\fR
.RS 4
The directory that buxtond will use for configuration storage\&.
.RE
.PP
\fI$BUXTON_SMACK_LOAD_FILE\fR
.RS 4
The path to the Smack "load2" file, typically residing on the Smack
virtual filesystem (smackfs)\&.
.RE
.PP
\fI$BUXTON_BUXTON_SOCKET\fR
.RS 4
The path to the Unix Domain Socket used by buxton clients to
communicate with buxtond\&.
.RE

.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.

.SH "COPYRIGHT"
.PP
Copyright 2014 Intel Corporation\&. License: Creative Commons
Attribution\-ShareAlike 3.0 Unported\s-2\u[1]\d\s+2\&.

.SH "SEE ALSO"
.PP
\fBbuxton\fR(7),
\fBbuxtond\fR(8),
\fBbuxton\-api\fR(7),
\fBbuxton\&.conf\fR(5)

.SH "NOTES"
.IP " 1." 4
Creative Commons Attribution\-ShareAlike 3.0 Unported
.RS 4
\%http://creativecommons.org/licenses/by-sa/3.0/
.RE
